const mongoose = require('mongoose');
require('dotenv').config();
const User = require('../models/User');
const Product = require('../models/Product');
const Outlet = require('../models/Outlet');

// Each product is now linked to an image inside the /image folder
// URL example from the frontend: http://localhost:5000/image/anaj/wheat.jpg
const products = [
  {
    name: 'Wheat',
    description: 'Premium quality organic wheat, perfect for daily rotis and chapatis',
    category: 'grains',
    price: 45,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 5,
    image: '/image/grains/10wheat1.jpg',
  },
  {
    name: 'Basmati Rice',
    description: 'Aromatic long-grain basmati rice, ideal for biryanis and pulao',
    category: 'grains',
    price: 120,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 2,
    image: '/image/grains/3basmatirice1.jpg',
  },
  {
    name: 'White Rice',
    description: 'Pure white rice, staple for everyday meals',
    category: 'grains',
    price: 50,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 5,
    image: '/image/grains/12rice1.jpg',
  },
  {
    name: 'Black Wheat',
    description: 'Nutritious black wheat with high fiber content',
    category: 'grains',
    price: 60,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 2,
    image: '/image/grains/4blackwheat1.jpg',
  },
  {
    name: 'Jowar (Sorghum)',
    description: 'Healthy jowar (juvar) grains, gluten-free alternative',
    category: 'grains',
    price: 40,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 2,
    image: '/image/grains/6juwar1.jpg',
  },
  {
    name: 'Bajra (Pearl Millet)',
    description: 'Nutritious bajra, rich in iron and fiber',
    category: 'grains',
    price: 35,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 2,
    image: '/image/grains/2bajro1.jpg',
  },
  {
    name: 'Ragi (Finger Millet)',
    description: 'High-protein ragi, excellent for health',
    category: 'grains',
    price: 55,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 2,
    image: '/image/grains/9ragi1.jpg',
  },
  {
    name: 'Toor Dal (Tuver Dal)',
    description: 'Split pigeon peas, essential for Indian cooking',
    category: 'pulses',
    price: 140,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/pulses/23tuverdal1.jpg',
  },
  {
    name: 'Moong Dal',
    description: 'Split green gram, light and easy to digest',
    category: 'pulses',
    price: 130,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/pulses/19mugdal1.jpg',
  },
  {
    name: 'Masoor Dal',
    description: 'Red lentils, quick cooking and nutritious',
    category: 'pulses',
    price: 120,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/pulses/18masurdal1.jpg',
  },
  {
    name: 'Urad Dal',
    description: 'Black gram dal, used in dals and vadas',
    category: 'pulses',
    price: 150,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/pulses/24uraddal1.jpg',
  },
  {
    name: 'Chana Dal',
    description: 'Split chickpeas, rich in protein',
    category: 'pulses',
    price: 110,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/pulses/14chanadal1.jpg',
  },
  {
    name: 'Rajma (Kidney Beans)',
    description: 'Red kidney beans, perfect for rajma curry',
    category: 'pulses',
    price: 160,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/pulses/21rajma1.jpg',
  },
  {
    name: 'Chana (Whole Chickpeas)',
    description: 'Whole chickpeas, great for snacks and curries',
    category: 'pulses',
    price: 100,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/pulses/13chanabig1.jpg',
  },
  // Oil Products
  {
    name: 'Sunflower Oil',
    description: 'Pure and healthy sunflower oil, perfect for cooking',
    category: 'oil',
    price: 180,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/oil/sunflower oil.jpg',
  },
  {
    name: 'Corn Oil',
    description: 'Light and healthy corn oil, ideal for daily cooking',
    category: 'oil',
    price: 160,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/oil/corn oil.jpg',
  },
  {
    name: 'Mustard Oil (Sarsav Oil)',
    description: 'Traditional mustard oil with strong flavor, perfect for Indian cuisine',
    category: 'oil',
    price: 200,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/oil/sarsav oil.jpg',
  },
  {
    name: 'Cottonseed Oil (Kapasiya Oil)',
    description: 'Refined cottonseed oil, neutral taste for versatile cooking',
    category: 'oil',
    price: 170,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/oil/kapasiya oil.jpg',
  },
  {
    name: 'Groundnut Oil',
    description: 'Pure groundnut oil, rich flavor and high smoke point',
    category: 'oil',
    price: 190,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/oil/groundatnt oil.jpg',
  },
  // Masala (Spices) Products
  {
    name: 'Turmeric Powder',
    description: 'Pure organic turmeric powder, essential for Indian cooking',
    category: 'masala',
    price: 300,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/massala/turmeric powder.jpg',
  },
  {
    name: 'Coriander Powder',
    description: 'Freshly ground coriander powder, aromatic and flavorful',
    category: 'masala',
    price: 280,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/massala/coriender powder.jpg',
  },
  {
    name: 'Cumin Powder',
    description: 'Pure cumin powder, adds distinct flavor to dishes',
    category: 'masala',
    price: 350,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/massala/cumin powder.jpg',
  },
  {
    name: 'Red Chilli Powder',
    description: 'Spicy red chilli powder, perfect heat for curries',
    category: 'masala',
    price: 320,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/massala/chilli powder.jpg',
  },
  {
    name: 'amchur',
    description: 'increse you taste',
    category: 'masala',
    price: 220,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/massala/Amchur.jpg',
  },
  {
    name: 'asafoetida',
    description: 'increse you taste',
    category: 'masala',
    price: 300,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/massala/Asafoetida.jpg',
  },
  {
    name: 'garam massala',
    description: 'increse you taste',
    category: 'masala',
    price: 290,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/massala/Garam Masala.jpg',
  },
  {
    name: 'Kashmiri Red Chilli powder',
    description: 'increse you taste',
    category: 'masala',
    price: 220,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/massala/Kashmiri Red Chilli powder.jpg',
  },
  {
    name: 'Kitchen King Masala',
    description: 'increse you taste',
    category: 'masala',
    price: 220,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/massala/Kitchen King Masala.jpg',
  },
   {
    name: 'rocksalt',
    description: 'increse you taste',
    category: 'masala',
    price: 220,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/massala/rocksalt.jpg',
  },




  // Dry Fruits Products
  {
    name: 'Almonds (Badam)',
    description: 'Premium quality almonds, rich in nutrients and healthy fats',
    category: 'dryfruits',
    price: 800,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.25,
    image: '/image/dryfruits/badam.jpg',
  },
  {
    name: 'Cashews (Kaju)',
    description: 'Creamy and delicious cashews, perfect for snacks and cooking',
    category: 'dryfruits',
    price: 1200,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.25,
    image: '/image/dryfruits/kaju.jpg',
  },
  {
    name: 'Walnuts (Akhrot)',
    description: 'Brain-healthy walnuts, rich in omega-3 fatty acids',
    category: 'dryfruits',
    price: 1000,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.25,
    image: '/image/dryfruits/akharot.png',
  },
  {
    name: 'Pistachios (Pista)',
    description: 'Delicious pistachios with unique flavor and vibrant color',
    category: 'dryfruits',
    price: 1400,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.25,
    image: '/image/dryfruits/pista.png',
  },
  {
    name: 'Raisins (Kishmish)',
    description: 'Sweet and juicy raisins, natural energy boosters',
    category: 'dryfruits',
    price: 400,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/dryfruits/kismis.jpg',
  },
  {
    name: 'Dates (Khajur)',
    description: 'Sweet and nutritious dates, natural energy source',
    category: 'dryfruits',
    price: 300,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/dryfruits/khajoor.jpg',
  },
   {
    name: 'Anjeer',
    description: 'Sweet and nutritious dates, natural energy source',
    category: 'dryfruits',
    price: 350,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/dryfruits/anjeer.jpg',
  },
   {
    name: 'black kishmis',
    description: 'Sweet and nutritious dates, natural energy source',
    category: 'dryfruits',
    price: 300,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/dryfruits/black kishmis.png',
  },
   {
    name: 'Aprikot',
    description: 'Sweet and nutritious dates, natural energy source',
    category: 'dryfruits',
    price: 300,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/dryfruits/aprikot.png',
  },

  // Other Products
  {
    name: 'Peanuts',
    description: 'Fresh roasted peanuts, great for snacking',
    category: 'others',
    price: 180,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/other/peanuts.jpg',
  },
  {
    name: 'Honey',
    description: 'Pure organic honey, natural sweetener with health benefits',
    category: 'others',
    price: 500,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/other/honey.jpg',
  },
  {
    name: 'Jaggery (Gud)',
    description: 'Organic jaggery, unrefined natural sweetener',
    category: 'others',
    price: 80,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 1,
    image: '/image/other/gud.jpg',
  },
  {
    name: 'Coriander Seeds (Dhana)',
    description: 'Whole coriander seeds, aromatic spice for cooking',
    category: 'others',
    price: 250,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/other/dhana.jpg',
  },
  {
    name: 'Mustard Seeds (Rai)',
    description: 'Whole mustard seeds, essential for tempering and pickles',
    category: 'others',
    price: 200,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/other/rai.jpg',
  },
  {
    name: 'Sesame Seeds (Tal)',
    description: 'White sesame seeds, nutritious and flavorful',
    category: 'others',
    price: 220,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/other/tal.jpg',
  },
  {
    name: 'Fennel Seeds (Variyali)',
    description: 'Sweet fennel seeds, great for digestion and flavor',
    category: 'others',
    price: 300,
    unit: 'kg',
    isOrganic: true,
    isAvailable: true,
    minOrderQuantity: 0.5,
    image: '/image/other/variyali.jpg',
  },
];

const connectDB = async () => {
  try {
    await mongoose.connect(
      process.env.MONGODB_URI || 'mongodb://localhost:27017/farmora-crops',
      {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      }
    );
    console.log('MongoDB Connected for seeding...');
  } catch (error) {
    console.error('MongoDB connection error:', error);
    process.exit(1);
  }
};

const seedData = async () => {
  try {
    await connectDB();

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert products
    const insertedProducts = await Product.insertMany(products);
    console.log(`Inserted ${insertedProducts.length} products`);

    // Create a sample outlet (you'll need to create a manager user first)
    // This is just a placeholder - in production, outlets should be created through the UI
    console.log('\n✅ Seeding completed!');
    console.log(
      '\nNote: To create outlets and users, use the registration API or create them manually.'
    );

    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

seedData();

